spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/djfy_vip?useUnicode=true&characterEncoding=utf8
    username: root
    password: MySql@2018
    driver-class-name: com.mysql.cj.jdbc.Driver
upload:
  w-upload: C:/upload
  l-upload: /home/upload
download: /file
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.djfy.vip.model
logging:
  path: C:/logs
  level:
    com.djfy.vip.dao: debug
jwt:
  secret: YWxsYSIsImV4cCI6MT
  expired_time: 18000000
  subject: tokenCheck
  issuer: vip
face:
  url: http://114.116.55.61:8083
  #url: http://192.168.1.186:8083
  app_id: 16fc2c5cd1bb4978ac7a9cfd6866eab7
  app_secret: EZWDJCDf4l/0KN3bT6nxo+HdRUopqszmCow/IDVApsnMe5I/ngytJBktNapEUc+TQF4nfec49dfGudcfJZdwspTgJVpEfF/ycEbSHYU/hIEOPPaBNf8EoQKvLJZDMygc4WhJNU8Vxeu3f1vXzPbNtNFcgqiDIf2ir9Uwk6e0Jqc=